import { NextRequest, NextResponse } from 'next/server';
import { readFile, writeFile } from 'fs/promises';
import { join, resolve } from 'path';
import { existsSync } from 'fs';

export async function POST(req: NextRequest) {
  try {
    // CSRF protection: require Origin from localhost
    const origin = req.headers.get('origin');
    if (!origin) {
      return NextResponse.json({ error: 'Origin header required' }, { status: 403 });
    }
    const originUrl = new URL(origin);
    if (originUrl.hostname !== 'localhost' && originUrl.hostname !== '127.0.0.1') {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    const body = await req.json();
    const projectPath: string = body.path;
    const mermaid: string = body.mermaid;

    if (!projectPath || !mermaid) {
      return NextResponse.json({ error: 'path and mermaid required' }, { status: 400 });
    }

    const basePath = resolve(projectPath);
    const readmePath = join(basePath, 'README.md');

    // Ensure README path stays within project
    if (!readmePath.startsWith(basePath)) {
      return NextResponse.json({ error: 'Invalid path' }, { status: 400 });
    }

    const marker = {
      start: '<!-- lattice:start -->',
      end: '<!-- lattice:end -->',
    };

    const block = [
      marker.start,
      '## Agent Architecture',
      '',
      '```mermaid',
      mermaid,
      '```',
      '',
      `*Auto-generated by [Lattice](https://github.com/your-username/lattice) — last updated ${new Date().toISOString().split('T')[0]}*`,
      marker.end,
    ].join('\n');

    let content: string;
    if (existsSync(readmePath)) {
      content = await readFile(readmePath, 'utf-8');
      // Replace existing block or append
      const startIdx = content.indexOf(marker.start);
      const endIdx = content.indexOf(marker.end);
      if (startIdx !== -1 && endIdx !== -1) {
        content = content.slice(0, startIdx) + block + content.slice(endIdx + marker.end.length);
      } else {
        content = content.trimEnd() + '\n\n' + block + '\n';
      }
    } else {
      content = block + '\n';
    }

    await writeFile(readmePath, content, 'utf-8');

    return NextResponse.json({ success: true, path: readmePath });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
